resources:
- repo: self

queue:
  name: Hosted VS2017
  demands: 
  - msbuild
  - visualstudio
  - npm

variables:
  BuildPlatform: 'any cpu'
  BuildConfiguration: 'release'
  major: 1
  minor: 1

name: $(major).$(minor)$(rev:.r)

steps:
- task: richardfennellBM.BM-VSTS-Versioning-Task.Version-Assemblies-Task.VersionAssemblies@2
  displayName: 'Version Assemblies'
  inputs:
    VersionRegex: '\d+\.\d+\.\d+'

- task: NuGetCommand@2
  displayName: 'NuGet restore'
  inputs:
    restoreSolution: '**\*.sln'

- task: VSBuild@1
  displayName: 'Build solution WorkItemMigrator'
  inputs:
    solution: src/WorkItemMigrator/WorkItemMigrator.sln
    platform: '$(BuildPlatform)'
    configuration: '$(BuildConfiguration)'

- task: ms-devlabs.vsts-developer-tools-build-tasks.package-extension-build-task.PackageVSTSExtension@1
  displayName: 'Package Extension: src/WorkItemMigrator.Extension'
  inputs:
    rootFolder: src/WorkItemMigrator.Extension
    outputPath: '$(Build.ArtifactStagingDirectory)\jira-devops-workitem-migrator-$(Build.BuildNumber).vsix'

- task: CopyFiles@2
  displayName: 'Copy JiraExport files'
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)\src\WorkItemMigrator\JiraExport\bin\$(BuildConfiguration)'
    Contents: |
***REMOVED***Atlassian.Jira.dll
***REMOVED***jira-export.exe
***REMOVED***jira-export.exe.config
***REMOVED***Microsoft.Extensions.CommandLineUtils.dll
***REMOVED***Migration.Common.dll
***REMOVED***Migration.WIContract.dll
***REMOVED***Newtonsoft.Json.dll
***REMOVED***RestSharp.dll
    TargetFolder: '$(build.artifactstagingdirectory)\WorkItemMigrator'
    flattenFolders: true

- task: CopyFiles@2
  displayName: 'Copy WorkItemImport files'
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)\src\WorkItemMigrator\WorkItemImport\bin\$(BuildConfiguration)'
    Contents: |
***REMOVED***Microsoft.TeamFoundation.Client.dll
***REMOVED***Microsoft.TeamFoundation.Common.dll
***REMOVED***Microsoft.TeamFoundation.Core.WebApi.dll
***REMOVED***Microsoft.TeamFoundation.WorkItemTracking.Client.DataStoreLoader.dll
***REMOVED***Microsoft.TeamFoundation.WorkItemTracking.Client.dll
***REMOVED***Microsoft.TeamFoundation.WorkItemTracking.Common.dll
***REMOVED***Microsoft.TeamFoundation.WorkItemTracking.Proxy.dll
***REMOVED***Microsoft.TeamFoundation.WorkItemTracking.WebApi.dll
***REMOVED***Microsoft.VisualStudio.Services.Common.dll
***REMOVED***Microsoft.VisualStudio.Services.WebApi.dll
***REMOVED***System.Net.Http.Formatting.dll
***REMOVED***wi-import.exe
***REMOVED***wi-import.exe.config
    TargetFolder: '$(build.artifactstagingdirectory)\WorkItemMigrator'
    flattenFolders: true

- task: CopyFiles@2
  displayName: 'Copy sample files'
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)\docs\samples'
    TargetFolder: '$(build.artifactstagingdirectory)\WorkItemMigrator\Samples'
    flattenFolders: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: WorkItemMigrator'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)\WorkItemMigrator'
    ArtifactName: WorkItemMigrator

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: WorkItemMigratorExtension'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)\jira-devops-workitem-migrator-$(Build.BuildNumber).vsix'
    ArtifactName: WorkItemMigratorExtension
